---
apiVersion: v1
data:
  entrypoint.sh: |
    #!/bin/bash

    rm -f /tmp/.X1-lock || true
    rm -f /tmp/.X11-unix/X1 || true

    pkill -f vncserver || true
    pkill -f Xvnc || true
    pkill -f websockify || true

    /opt/TurboVNC/bin/vncserver -securitytypes tlsnone,x509none,none && \
      websockify -D \
        --web=/usr/share/novnc/ \
        --cert=~/novnc.pem 80 localhost:5901 && /startapp.sh

    tail -f /dev/null

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: nos3-m01-sc01-fortytwo
  name: nos3-fortytwo-cm0
---
apiVersion: v1
data:
  startapp.sh: |+
    #!/bin/bash
    export DISPLAY=:1
    DIR=/opt/nasa-itc
    cd ${DIR}/42 
    xterm &
    xterm -e ./42 X &
    echo "Started 42 in xterm with PID $!"

    tail -f /dev/null
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: nos3-m01-sc01-fortytwo
  name: nos3-fortytwo-cm1
