---
apiVersion: v1
kind: Service
metadata:
  name: nos3-m01-sc1-generic-reactionwheel-sim1
  namespace: ssmo-dev-missions-exp-nos3-m01-sc1
spec:
  selector:
    app: ssmo-dev-missions-exp-nos3-m01-sc1-generic-reactionwheel-sim1
  ports:
    - name: healthcheck-tcp
      protocol: TCP
      port: 60000
      targetPort: 60000
    - name: healthcheck-udp
      protocol: UDP
      port: 60000
      targetPort: 60000
  type: ClusterIP

