metadata:
  OU: myorg
  ENVIRO: dev
  TENANT: tenant
  CONTEXT: missions # -exp must exist to match remote AWS EKS cluster
  PURPOSE: -exp

defaults:
  spec:    
    HEALTHCHECK_PORT: &HEALTHCHECK_PORT
      60000
    PATHS: &PATHS
      BASE_DIR: &BASE_DIR
        /builds/nos3
      SIM_BIN: &SIM_BIN
        /builds/nos3/sims/build/bin
      SIMULATOR_BIN: &SIMULATOR_BIN
        /builds/nos3/sims/build/bin/nos3-single-simulator
      LOG_CONFIG: &LOG_CONFIG
        /builds/nos3/sims/build/bin/sim_log_config.xml
      # CFG_FILE: &CFG_FILE
      #   /builds/nos3/sims/build/bin/nos3-simulator.xml
      SC_CFG_FILE: &SC_CFG_FILE
        /builds/nos3/sims/build/bin/nos3-simulator.xml
      GND_CFG_FILE: &GND_CFG_FILE
        /builds/nos3/sims/build/bin/nos3-simulator.xml
      IMAGE_REGISTRY: &IMAGE_REGISTRY
        ghcr.io
      IMAGE_URI: &IMAGE_URI
        ghcr.io/ericstoneking/42:latest
    container: &container
      PATHS: 
        << : *PATHS
      resources: &resources
        limits: &limits
          memory: "128Mi"
          cpu: "100m"
        requests: &requests
          memory: "128Mi"
          cpu: "100m"
    nodes: &nodes
      min_size: 1
      max_size: 1
      desired_size: 1
      instance_types: m6i.xlarge
      nodeSelector: ""
      imagePullPolicy: IfNotPresent
      components: &hw_components
        fortytwo:
          name: fortytwo
          host: fortytwo
          replicas: 1
          container: 
            PATHS: 
              BASE_DIR: &BASE_DIR
                /builds/nos3
              SIM_BIN: &SIM_BIN
                /builds/nos3/sims/build/bin
              SIMULATOR_BIN: &SIMULATOR_BIN
                /builds/nos3/sims/build/bin/nos3-single-simulator
              LOG_CONFIG: &LOG_CONFIG
                /builds/nos3/sims/build/bin/sim_log_config.xml
              # CFG_FILE: &CFG_FILE
              #   /builds/nos3/sims/build/bin/nos3-simulator.xml
              SC_CFG_FILE: &SC_CFG_FILE
                /builds/nos3/sims/build/bin/nos3-simulator.xml
              GND_CFG_FILE: &GND_CFG_FILE
                /builds/nos3/sims/build/bin/nos3-simulator.xml
              IMAGE_REGISTRY: &IMAGE_REGISTRY
                ghcr.io
              IMAGE_URI: &IMAGE_URI
                ghcr.io/ericstoneking/42:latest
            resources: &resources
              limits: &limits
                memory: "128Mi"
                cpu: "100m"
              requests: &requests
                memory: "128Mi"
                cpu: "100m"


missions:
  - m01:
      enabled: true
      spacecraft:
        - sc1:
            enabled: true
            components: 
              << : *hw_components

  - m02:
      enabled: false
      spacecraft:
        - sc1:
            enabled: true
            components: 
              << : *hw_components
        - sc2:
            enabled: false
            components: 
              << : *hw_components