name: nos3-m01-sc01

services:
  nos3-fortytwo:
    image: ghcr.io/haisamido/nos3-base-fortytwo:dev
    attach: true
    container_name: sc01-fortytwo
    hostname: fortytwo
    working_dir: "/opt/nasa-itc/"
    command: '/entrypoint.sh'
    volumes:
      - ${PWD}/../../cfg/InOut/:/opt/nasa-itc/42/InOut/
      - ${PWD}/../nos3/cfg/InOut/Inp_IPC.txt:/opt/nasa-itc/42/InOut/Inp_IPC.txt      
      - ${PWD}/42/entrypoint.sh:/entrypoint.sh
      - ${PWD}/42/startapp.sh:/startapp.sh  
    ports:
      - "30090:80"
    environment:
      DISPLAY: ":1"
    networks:
      nos3-sc01:
        aliases: 
          - fortytwo
      nos3-core:

  nos3-fsw:
    image: ghcr.io/haisamido/nos3-base-fsw-uart:dev
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_started
    container_name: sc01-nos-fsw
    hostname: nos-fsw
    working_dir: /home/nos3/builds/nos3/
    volumes:
      - ${PWD}/fsw/entrypoint.sh:/entrypoint.sh
    command: "/entrypoint.sh"
    sysctls:
      fs.mqueue.msg_max: 10000
    ulimits:
      rtprio: 99
    cap_add:
      - sys_nice
    environment:
      BASE_DIR: /home/nos3/builds/nos3
      FSW_DIR: /home/nos3/builds/nos3/fsw/build/exe/cpu1
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - nos-fsw
      nos3-core:

  nos3-nos_engine_server:
    image: ghcr.io/haisamido/nos3-base:dev
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_started
    container_name: sc01-nos-engine-server
    hostname: nos-engine-server
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "/usr/bin/nos_engine_server_standalone -f ./nos_engine_server_config.json"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos_engine_server_config.json:/home/nos3/builds/nos3/sims/build/bin/nos_engine_server_config.json
    tty: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - nos_engine_server
          - sc01-nos-engine-server
      nos3-core:

  nos3-gps:
    image: ghcr.io/haisamido/nos3-base:dev
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_started
      nos3-fsw:
        condition: service_started
    container_name: sc01-gps-sim
#    hostname: sc01-gps-sim 
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml gps"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - gps
      nos3-core:

  nos3-time:
    image: ghcr.io/haisamido/nos3-base:dev
    attach: true
    depends_on:
      nos3-nos_engine_server:
        condition: service_started
    container_name: nos-time-driver
    hostname: nos-time-driver
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml time"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - sc01-nos-time-driver
      nos3-core:

  nos3-gsw:
    image: ghcr.io/haisamido/nos3-base-yamcs:dev
    attach: true
    depends_on:
      nos3-gps:
        condition: service_started
      nos3-fsw:
        condition: service_started
      nos3-truth42sim:
        condition: service_started
    container_name: cosmos_openc3-operator_1
    hostname: cosmos
    working_dir: "/home/nos3/.nos3/yamcs"
    command: "/entrypoint.sh"
    volumes:
      - ${PWD}/yamcs/entrypoint.sh:/entrypoint.sh
      - ${PWD}/yamcs/settings.xml:/home/nos3/.nos3/yamcs/settings.xml
    ports:
      - "8090:8090"
    tty: true
    stdin_open: true
    privileged: true
    environment:
      COMPONENT_DIR: "/home/nos3/builds/nos3/components"
      YAMCS_DATA_DIR: "/home/nos3/.nos3/yamcs/target/yamcs/yamcs-data"
      # YAMCS_ETC_DIR:
      # YAMCS_CACHE_DIR:
      MAVEN_REPO_LOCAL: "/home/nos3/.nos3/.m2/repository"
      MAVEN_HTTPS_PROXY: "--settings ./settings.xml"
      HTTPS_PROXY: ""
      HTTP_PROXY: ""
      DEPLOYMENT_ENVIRO: ""
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - cosmos
          - yamcs
      nos3-core:

  nos3-truth42sim:
    image: ghcr.io/haisamido/nos3-base:dev
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_started
      nos3-nos_engine_server:
        condition: service_started
      nos3-gps:
        condition: service_started
      nos3-time:
        condition: service_started
      nos3-fsw:
        condition: service_started
    container_name: sc01-truth42sim
    hostname: truth42sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml truth42sim"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3-sc01
      - nos3-core

  nos3-nos_terminal:
    image: ghcr.io/haisamido/nos3-base:dev
    attach: true
    container_name: nos-terminal
    hostname: nos-terminal
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml  truth42sim"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - nos-terminal
      nos3-core:

  nos3-nos_udp_terminal:
    image: ghcr.io/haisamido/nos3-base:dev
    attach: true
    container_name: nos-udp-terminal
    hostname: nos-udp-terminal
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml  truth42sim"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      nos3-sc01:
        aliases: 
          - nos-udp-terminal
      nos3-core:
  
networks:
  nos3-core:
    driver: bridge
  nos3-sc01:
