---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nos3-m01-sc01
  name: nos3-gps
  labels:
    app: nos3-m01-sc01-gps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nos3-m01-sc01-gps
  template:
    metadata:
      labels:
        app: nos3-m01-sc01-gps
    spec:
      containers:
        - env:
            - name: BASE_DIR
              value: /builds/nos3
            - name: CFG_FILE
              value: /builds/nos3/sims/build/bin/nos3-simulator.xml
            - name: COMPONENT_NAME
              value: gps
            - name: HEALTHCHECK_PORT
              value: "60000"
            - name: LOG_CONFIG
              value: /builds/nos3/sims/build/bin/sim_log_config.xml
            - name: SIMULATOR_BIN
              value: /builds/nos3/sims/build/bin/nos3-single-simulator
            - name: SIM_BIN
              value: /builds/nos3/sims/build/bin
          image: registry.appdat.jsc.nasa.gov/ssmo/images/ssmo/nos3/nos3-base:20250217
          name: 03-sc01-gps-sim
          resources:
            limits:
              cpu: 100m
              memory: "128Mi"
            requests:
              cpu: 100m
              memory: "Mi"
          securityContext:
            privileged: true
      hostname: gps
      restartPolicy: Always
